apiVersion: v1
kind: Service
metadata:
    name: jmxapp01-9090
    labels:
        run: jmxapp01
spec:
    type: NodePort
    ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
    selector:
      run: jmxapp01
