apiVersion: v1
kind: Service
metadata:
    name: jmxapp01-1234
    labels:
        run: jmxapp01
spec:
    type: NodePort
    ports:
    - port: 1234
      targetPort: 1234
      protocol: TCP
      name: http
    selector:
      run: jmxapp01
